sudo: required
services:
  - docker
before_install:
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gloud components update kubectl
  - gcloud auth aactivate-service-account --key-file service-account.json